import { StyleSheet } from 'react-native';
import { colors, fontSize, hp, radius, wp } from '../../constant';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollViewContainer: {
    flexGrow: 1,
  },
  topView: {
    height: hp(35),
    paddingHorizontal: wp(4),
    backgroundColor: colors.pink,
  },
  headerView: {
    paddingTop: hp(2),
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  backButton: {
    width: wp(12),
    height: hp(6),
    borderRadius: radius.radius7,
    backgroundColor: colors.softPink,
    justifyContent: 'center',
    alignItems: 'center',
  },
  walletText: {
    color: colors.white,
    fontWeight: '700',
    fontSize: fontSize.medium,
  },
  bottomContainer: {
    bottom: hp(18),
    marginHorizontal: wp(5),
    borderRadius: radius.radius8,
    backgroundColor: colors.veryDark,
  },
  bikeView: {
    backgroundColor: colors.almostBlack,
    alignItems: 'center',
    marginVertical: hp(2),
    marginHorizontal: wp(4),
    borderRadius: radius.radius8,
    paddingBottom: hp(1.5),
  },
  confirmTextView: {
    paddingHorizontal: wp(3),
    paddingVertical: hp(0.3),
    position: 'absolute',
    right: wp(2),
    top: hp(1.5),
    borderRadius: radius.radius8,
    backgroundColor: colors.viewbackground,
  },
  confirmText: {
    color: colors.darkGreen,
    fontWeight: '600',
  },
  modalText: {
    fontWeight: '700',
    color: colors.white,
    textAlign: 'center',
    fontSize: fontSize.statusSize,
  },
  companyText: {
    marginTop: hp(1),
    fontWeight: '400',
    textAlign: 'center',
    color: colors.lightGray,
    fontSize: fontSize.avgSmall,
  },
  dateText: {
    fontWeight: '400',
    textAlign: 'center',
    color: colors.lightGray,
    fontSize: fontSize.avgSmall,
  },
  qrImage: {
    height: hp(22),
    width: wp(44),
    alignSelf: 'center',
    marginTop: hp(4),
  },
  scanText: {
    fontWeight: '400',
    color: colors.white,
    textAlign: 'center',
    marginTop: hp(2),
    marginBottom: hp(3.5),
    lineHeight: hp(2.5),
    fontSize: fontSize.regSmall,
  },
  bottomView: {
    backgroundColor: colors.veryDark,
    paddingHorizontal: wp(5),
    paddingVertical: hp(2),
    borderRadius: radius.radius2,
    bottom: hp(16),
    marginHorizontal: wp(5),
    borderRadius: radius.radius8,
  },
  addText: {
    fontWeight: '500',
    color: colors.silverColor,
    fontSize: fontSize.small,
  },
  productNameText: {
    fontWeight: '500',
    color: colors.graniteGray,
    fontSize: fontSize.regSmall,
    paddingTop: hp(1),
    textAlign: 'center',
  },
  itemContainer: {
    flexDirection: 'row',
    gap: wp(6),
    marginTop: hp(0.5),
    paddingHorizontal: wp(3),
    paddingVertical: wp(3),
    borderRadius: radius.radius2,
    backgroundColor: colors.charlestonGreen1,
  },
  contactOwnerContainer: {
    backgroundColor: colors.veryDark,
    paddingHorizontal: wp(5),
    paddingTop: hp(1),
    paddingBottom: hp(2.5),
    borderRadius: radius.radius2,
    bottom: hp(14),
    marginHorizontal: wp(5),
    borderRadius: radius.radius8,
  },
  contactOwnerText: {
    color: colors.white,
    fontWeight: '700',
    fontSize: fontSize.small,
  },
  nameText: {
    fontWeight: '700',
    color: colors.white,
    fontSize: fontSize.mediumSmall,
  },
  personText: {
    fontWeight: '400',
    color: colors.lightGray,
    fontSize: fontSize.avgSmall,
  },
  personView: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(5),
    paddingTop: hp(1),
  },
  chatText: {
    fontWeight: '500',
    fontSize: fontSize.avgSmall,
    color: colors.quickSilver,
  },
  chatTextView: {
    flexDirection: 'row',
    gap: wp(3),
    alignItems: 'center',
  },
  line: {
    paddingTop: hp(2),
  },
  chatView: {
    backgroundColor: colors.charlestonGreen1,
    paddingHorizontal: wp(4),
    paddingVertical: hp(1.5),
    borderRadius: radius.radius2,
    marginTop: hp(1),
  },
  bookingContainer: {
    backgroundColor: colors.veryDark,
    paddingHorizontal: wp(5),
    paddingTop: hp(1),
    paddingBottom: hp(2.5),
    borderRadius: radius.radius2,
    bottom: hp(12),
    marginHorizontal: wp(5),
    borderRadius: radius.radius8,
  },
  downloadButton: {
    backgroundColor: colors.deepPink,
    borderRadius: radius.radius9,
    paddingVertical: hp(1.5),
    marginHorizontal: wp(5),
    alignItems: 'center',
    marginBottom: hp(3),
  },
  downloadBottonText: {
    color: colors.white,
    fontSize: fontSize.statusSize,
    fontWeight: '700',
  },
  overlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: colors.modalBackGroundColor,
  },
  modalTextView: {
    backgroundColor: colors.nero1,
    paddingHorizontal:wp(3),
    paddingVertical:hp(3),
    marginBottom:hp(2.5),
    borderRadius:radius.radius2
  },
  modalContainer: {
    backgroundColor: colors.RaisinBlack,
    borderRadius: radius.radius7,
    paddingHorizontal: wp(6),
    paddingVertical: hp(4),
  },
  title: {
    fontWeight: '700',
    fontSize: fontSize.mediumSmall,
    color: colors.antiFlashWhite,
    marginBottom: hp(1),
  },
  subtitle: {
    fontSize: fontSize.small,
    color: colors.lightGray,
    fontWeight: '400',
    marginBottom: hp(1),
  },
  productContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: wp(3),
    backgroundColor: colors.charlestonGreen1,
    borderRadius: radius.radius2,
  },
  productName: {
    fontWeight: '500',
    fontSize: fontSize.mediumSmall,
    color: colors.antiFlashWhite,
  },
  productDetails: {
    fontSize: fontSize.avgSmall,
    color: colors.lightGray,
    fontWeight: '400',
    marginBottom: hp(1),
  },
  price: {
    fontSize: fontSize.mediumSmall,
    color: colors.whiteShade,
    fontWeight: '600',
  },
  buttonContainer: {
    flexDirection: 'row',
    gap: wp(2),
  },
  goBackButton: {
    backgroundColor: colors.graniteGray,
    borderRadius: radius.radius9,
  },
  goBackText: {
    fontWeight: '700',
    paddingHorizontal: wp(8),
    paddingVertical: hp(2),
    color: colors.white,
    fontSize: fontSize.mediumSmall,
  },
  cancelButton: {
    borderRadius: radius.radius9,
    backgroundColor: colors.deepPink,
  },
  cancelText: {
    fontWeight: '700',
    paddingHorizontal: wp(10),
    paddingVertical: hp(2),
    color: colors.white,
    fontSize: fontSize.mediumSmall,
  },
});
