import { StyleSheet } from 'react-native';
import { colors, fontSize, hp, radius, wp } from '../../constant';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollViewContainer: {
    flexGrow: 1,
  },
  topView: {
    height: hp(35),
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: wp(4),
    backgroundColor: colors.pink,
  },
  backButton: {
    width: wp(12),
    height: hp(6),
    borderRadius: radius.radius7,
    backgroundColor: colors.softPink,
    justifyContent: 'center',
    alignItems: 'center',
  },
  walletText: {
    color: colors.white,
    fontWeight: '700',
    fontSize: fontSize.medium,
  },
  bottomContainer: {
    // zIndex: 1,
    bottom: hp(25),
    marginHorizontal: wp(5),
    borderRadius: radius.radius8,
    backgroundColor: colors.veryDark,
  },
  bikeView: {
    backgroundColor: colors.almostBlack,
    alignItems: 'center',
    marginVertical: hp(2),
    marginHorizontal: wp(4),
    borderRadius: radius.radius8,
    paddingBottom: hp(1.5),
  },
  confirmTextView: {
    paddingHorizontal: wp(3),
    paddingVertical: hp(0.3),
    position: 'absolute',
    right: wp(2),
    top: hp(1.5),
    borderRadius: radius.radius8,
    backgroundColor: colors.viewbackground,
  },
  confirmText: {
    color: colors.darkGreen,
    fontWeight: '600',
  },
  modalText: {
    fontWeight: '700',
    color: colors.white,
    textAlign: 'center',
    fontSize: fontSize.statusSize,
  },
  companyText: {
    marginTop: hp(1),
    fontWeight: '400',
    textAlign: 'center',
    color: colors.lightGray,
    fontSize: fontSize.avgSmall,
  },
  dateText: {
    fontWeight: '400',
    textAlign: 'center',
    color: colors.lightGray,
    fontSize: fontSize.avgSmall,
  },
  qrImage: {
    height: hp(22),
    width: wp(44),
    alignSelf: 'center',
    marginTop: hp(4),
  },
  scanText: {
    fontWeight: '400',
    color: colors.white,
    textAlign: 'center',
    marginTop: hp(2),
    marginBottom: hp(3.5),
    lineHeight: hp(2.5),
    fontSize: fontSize.regSmall,
  },
  bottomView: {
    backgroundColor: colors.veryDark,
    paddingHorizontal: wp(5),
    paddingVertical: hp(2),
    borderRadius: radius.radius2,
    bottom: hp(23),
    marginHorizontal: wp(5),
    borderRadius: radius.radius8,
  },
  addText: {
    fontWeight: '500',
    color: colors.silverColor,
    fontSize: fontSize.small,
  },
  productNameText: {
    fontWeight: '500',
    color: colors.graniteGray,
    fontSize: fontSize.regSmall,
    paddingTop: hp(1),
    textAlign: 'center',
  },
  itemContainer: {
    flexDirection: 'row',
    gap: wp(6),
    marginTop: hp(0.5),
    paddingHorizontal: wp(3),
    paddingVertical: wp(3),
    borderRadius: radius.radius2,
    backgroundColor: colors.charlestonGreen1,
  },
  contactOwnerContainer: {
    backgroundColor: colors.veryDark,
    paddingHorizontal: wp(5),
    paddingTop: hp(1),
    paddingBottom:hp(2.5),
    borderRadius: radius.radius2,
    bottom: hp(21),
    marginHorizontal: wp(5),
    borderRadius: radius.radius8,
  },
  contactOwnerText: {
    color: colors.white,
    fontWeight: '700',
    fontSize: fontSize.small,
  },
  nameText: {
    fontWeight: '700',
    color: colors.white,
    fontSize: fontSize.mediumSmall,
  },
  personText: {
    fontWeight: '400',
    color: colors.lightGray,
    fontSize: fontSize.avgSmall,
  },
  personView: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(5),
    paddingTop: hp(1),
  },
  chatText: {
    fontWeight: '500',
    fontSize: fontSize.avgSmall,
    color: colors.quickSilver,
  },
  chatTextView: {
    flexDirection: 'row',
    gap: wp(3),
    alignItems: 'center',
  },
  line: {
    paddingTop:hp(2),
  },
  chatView:{
    backgroundColor:colors.charlestonGreen1,
    paddingHorizontal:wp(4),
    paddingVertical:hp(1.5),
    borderRadius:radius.radius2,
    marginTop:hp(1)
  },
   bookingContainer: {
    backgroundColor: colors.veryDark,
    paddingHorizontal: wp(5),
    paddingTop: hp(1),
    paddingBottom:hp(2.5),
    borderRadius: radius.radius2,
    bottom: hp(19),
    marginHorizontal: wp(5),
    borderRadius: radius.radius8,
  },
  downloadButton: {
    backgroundColor: colors.deepPink,
    borderRadius: radius.radius9,
    paddingVertical: hp(1.5),
    marginHorizontal: wp(5),
    alignItems: 'center',
    marginBottom:hp(3)
  },
  downloadBottonText: {
    color: colors.white,
    fontSize: fontSize.statusSize,
    fontWeight: '700',
  },
});
